# vim: set syntax=dockerfile:
FROM tensorflow/tensorflow:2.1.0-gpu-py3

RUN apt-get update \
    && apt-get install -y \
        gir1.2-gtk-3.0 \
        git \
        gobject-introspection \
        libgirepository1.0-dev \
        libcairo2-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

COPY main .
COPY src src
COPY data/vectorizer.pickle data/vectorizer.pickle
COPY data/selector.pickle data/selector.pickle
COPY data/model.h5 data/model.h5

ENTRYPOINT ["./main", "serve"]
