# vim: set syntax=dockerfile:
FROM golang:1.14-alpine as build
RUN apk add --no-cache gcc libc-dev
COPY plugin /build
WORKDIR /build
RUN go build -tags "netgo" -ldflags '-s -w -linkmode external -extldflags "-static -lm"'

FROM scratch
COPY --from=build /build/plugin /main
ENTRYPOINT ["/main"]
