# vim: set syntax=dockerfile:
FROM tensorflow/tensorflow:2.1.0-py3

COPY requirements-deploy.txt /

RUN pip install --no-cache-dir -r requirements-deploy.txt

WORKDIR /app

COPY main .
COPY src src
COPY data/vectorizer.pickle data/vectorizer.pickle
COPY data/selector.pickle data/selector.pickle
COPY data/model.h5 data/model.h5

ENTRYPOINT ["./main", "serve"]
