# vim: set syntax=dockerfile:
FROM golang:1.14-alpine as build
RUN apk add --no-cache gcc libc-dev make
COPY plugin /build
WORKDIR /build
RUN make

FROM alpine
RUN apk add --no-cache ca-certificates
COPY --from=build /build/plugin /main
ENTRYPOINT ["/main"]
