#!/usr/bin/env python3
import argparse
from typing import Any

from src.ml import ML


def main():
    args = parse_args()
    result = ML.predict(args.text)
    print(result)


def parse_args() -> Any:
    parser = argparse.ArgumentParser()
    parser.add_argument("text", type=str, help="The text to predict")
    return parser.parse_args()


if __name__ == "__main__":
    main()
