#!/usr/bin/env python3
import argparse
import logging
from typing import Any

import src.log as log
from src.data import Data

DEFAULT_LABEL = "kind/bug"


def main():
    args = parse_args()
    log.setup(logging.INFO)
    Data().train_release_notes_by_label(args.label, tune=args.tune)


def parse_args() -> Any:
    parser = argparse.ArgumentParser()
    parser.add_argument("--tune",
                        "-t",
                        action="store_true",
                        help="Tune the hyper parameters")
    parser.add_argument("--label",
                        "-l",
                        type=str,
                        default=DEFAULT_LABEL,
                        help="The label to classify (default: '%s')" %
                        DEFAULT_LABEL)

    return parser.parse_args()


if __name__ == "__main__":
    main()
