---
version: 2.1

workflows:
  main:
    jobs:
      - update:
          name: test
  update:
    jobs:
      - update:
          commit: true
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

executors:
  machine:
    machine:
      image: ubuntu-1604:201903-01

jobs:
  update:
    parameters:
      commit:
        type: boolean
        default: false
    executor: machine
    steps:
      - add_ssh_keys:
          fingerprints:
            - 5f:6f:8d:60:03:5c:11:96:d5:bb:45:b7:0f:8f:9b:17
      - checkout
      - run:
          name: Setup dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              gir1.2-gtk-3.0 \
              gobject-introspection \
              libgirepository1.0-dev

            pushd $(pyenv root)
            git pull
            popd

            export VERSION=3.8.2
            pyenv install $VERSION
            pyenv local $VERSION

            python --version
            pip install -r requirements.txt
      - run:
          name: Update API
          command: ./main export --update-api
      - run:
          name: Update data
          command: ./main export --update-data
      - run:
          name: Update assets
          command: make assets
      - run:
          name: Test Model
          command: ./main predict --test
      - run:
          name: Build Pipeline
          command: ./main pipeline
      - run:
          name: Commit changes
          command: |
            if << parameters.commit >>; then
              git config --global user.name "Sascha Grunert"
              git config --global user.email mail@saschagrunert.de
              git add .
              git commit -m "Update data" || true
              git push -u origin master
            fi
