---
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kubernetes-analysis
  namespace: kfserving
spec:
  canaryTrafficPercent: 0
  default:
    predictor:
      custom:
        container:
          image: quay.io/saschagrunert/kubernetes-analysis-kfserving:latest
          imagePullPolicy: Always
  canary:
    predictor:
      custom:
        container:
          image: quay.io/saschagrunert/kubernetes-analysis-kfserving:latest
          imagePullPolicy: Always
