---
prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

tide:
  target_url: https://prow.k8s.saschagrunert.de/tide
  queries:
    - orgs:
        - kubernetes-analysis
      labels:
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
  merge_method:
    kubernetes-analysis: squash

github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

plank:
  default_decoration_configs:
    '*':
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20200430-17bd0eb2b
        initupload: gcr.io/k8s-prow/initupload:v20200430-17bd0eb2b
        entrypoint: gcr.io/k8s-prow/entrypoint:v20200430-17bd0eb2b
        sidecar: gcr.io/k8s-prow/sidecar:v20200430-17bd0eb2b
      gcs_configuration:
        bucket: k8s-conform-cri-o
        path_strategy: explicit
        path_prefix: prow
      gcs_credentials_secret: gcs-credentials

presubmits:
  kubernetes-analysis/kubernetes-analysis:
    - name: echo-test
      decorate: true
      always_run: true
      spec:
        containers:
          - image: alpine
            command: ["/bin/date"]
