---
prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

tide:
  target_url: https://prow.k8s.saschagrunert.de
  merge_method:
    kubernetes-analysis: squash
  queries:
    - orgs:
        - kubernetes-analysis
      labels:
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase

github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

plank:
  job_url_template: "https://prow.k8s.saschagrunert.de/log?job={{.Spec.Job}}&id={{.Status.BuildID}}"

presubmits:
  kubernetes-analysis/kubernetes-analysis:
    - name: pipeline-test
      decorate: false
      always_run: true
      spec:
        containers:
          - image: quay.io/saschagrunert/kubernetes-analysis:latest
            imagePullPolicy: Always
            command:
              - /bin/bash
              - -c
              - |
                set -euox pipefail

                mkdir repo
                pushd repo

                git init
                REPO=kubernetes-analysis
                git remote add origin https://github.com/$REPO/$REPO
                git fetch --depth=1 origin pull/$PULL_NUMBER/head:$PULL_NUMBER
                git checkout $PULL_NUMBER

                git status
            volumeMounts:
              - name: kubeconfig
                mountPath: /root/.kube
                readOnly: true
        volumes:
          - name: kubeconfig
            secret:
              secretName: kubeconfig
