---
prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

tide:
  target_url: https://prow.k8s.saschagrunert.de
  merge_method:
    kubernetes-analysis: squash
  queries:
    - orgs:
        - kubernetes-analysis
      labels:
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase

github_reporter:
  job_types_to_report:
    - presubmit
    - postsubmit

plank:
  job_url_template: "https://prow.k8s.saschagrunert.de/log?job={{.Spec.Job}}&id={{.Status.BuildID}}"

stdenv: &stdenv
  image: quay.io/saschagrunert/kubernetes-analysis:latest
  imagePullPolicy: Always
  volumeMounts:
    - name: kubeconfig
      mountPath: /root/.kube
      readOnly: true

volumes: &volumes
  volumes:
    - name: kubeconfig
      secret:
        secretName: kubeconfig

periodics:
  - name: data-update
    interval: 24h
    decorate: false
    spec:
      <<: *volumes
      containers:
        - <<: *stdenv
          command:
            - /bin/bash
            - -c
            - |
              set -euox pipefail
              REPO=kubernetes-analysis
              git clone --depth=1 https://github.com/$REPO/$REPO
              pushd $REPO

              make pipeline-run

postsubmits:
  kubernetes-analysis/kubernetes-analysis:
    - name: pipeline
      decorate: false
      branches:
        - ^master$
      spec:
        <<: *volumes
        containers:
          - <<: *stdenv
            command:
              - /bin/bash
              - -c
              - |
                set -euox pipefail
                REPO=kubernetes-analysis
                git clone --depth=1 https://github.com/$REPO/$REPO
                pushd $REPO

                if ! git log -1 --pretty=oneline | grep -q "[skip]"; then
                  make pipeline-run
                fi

presubmits:
  kubernetes-analysis/kubernetes-analysis:
    - name: pipeline-test
      decorate: false
      always_run: true
      spec:
        <<: *volumes
        containers:
          - <<: *stdenv
            command:
              - /bin/bash
              - -c
              - |
                set -euox pipefail
                REPO=kubernetes-analysis
                URL=https://github.com/$REPO/$REPO
                git clone --depth=1 $URL
                pushd $REPO
                curl -L $URL/pull/$PULL_NUMBER.patch > ../pr.patch
                git apply ../pr.patch
                git add .
                git commit -m "Apply patch"
                make pipeline-run

    - name: lint
      decorate: false
      always_run: true
      spec:
        <<: *volumes
        containers:
          - <<: *stdenv
            command:
              - /bin/bash
              - -c
              - |
                set -euox pipefail
                REPO=kubernetes-analysis
                URL=https://github.com/$REPO/$REPO
                git clone --depth=1 $URL
                pushd $REPO
                curl -L $URL/pull/$PULL_NUMBER.patch > ../pr.patch
                git apply ../pr.patch
                git add .
                git commit -m "Apply patch"
                make lint
