#!/usr/bin/env bash
set -euox pipefail
shopt -s globstar

# lint
pylint ./**/*.py
flake8 ./**/*.py

VERSION=v1.26.0
URL=https://raw.githubusercontent.com/golangci/golangci-lint
export BINDIR=bin
curl -sfL $URL/$VERSION/install.sh | sh -s $VERSION
bin/golangci-lint linters
bin/golangci-lint run

# format
isort -y -rc
yapf -i -r .

# validate
ci/tree-status
