#!/usr/bin/env bash
set -euo pipefail

STATUS=$(git status --porcelain)
if [[ -z $STATUS ]]; then
    echo "tree is clean"
else
    echo "tree is dirty, please commit all changes"
    git diff
    exit 1
fi
